name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "1.22"
    env:
      GOPRIVATE: github.com/reddit/achilles-sdk-api

    container:
      image: golang:${{ matrix.go-version }}

    steps:
      - uses: actions/checkout@v3

      - name: Workaround Git Security Warning
        run: |
          # Workaround a bug in github actions:
          # https://github.com/actions/runner-images/issues/6775.
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Setup access for private Go modules
        run: |
          git config --global url."ssh://git@github.com/".insteadOf https://github.com/

      - name: Generate
        run: |
          # needed for running `tar -xJv` for installing shellcheck
          apt-get update
          apt-get install xz-utils
          
          make generate
          git status
          git diff
          test -z "$(git status --porcelain)"

          # lint code
          make lint
          git status
          git diff
          test -z "$(git status --porcelain)"
